### ISSUE TITLE
flux cd GitRepository issue on 19.0.x releases 

### ISSUE THREAD

**Issue by alokhom** [keycloak/keycloak-k8s-resources#13]
### Describe the bug

facing this problem when setting a GitRepository
failed to checkout and determine revision: unable to clone 'https://github.com/keycloak/keycloak-k8s-resources': Get "https://github.com/keycloak/keycloak-k8s-resources/info/refs?service=git-upload-pack": x509: certificate is valid for ingress.local, not github.com

since release of 19.0.3 version 

### Version

19.0.3

### Expected behavior

normal downloads to a GitRepository

### Anything else?
using minikube v1.22.0
_No response_

**Comment by vmuzikar** [comment]
Hello, if this is still valid, could you please open an issue in the [main Keycloak repository](https://github.com/keycloak/keycloak)? This repository is not monitored or used for tracking issues.

Thank you.
