### ISSUE TITLE
latest version should also be pushed to main branch

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak-k8s-resources#14]
### Describe the bug

The main branch contains old code

### Version

main

### Expected behavior

To work as any github repo

### Actual behavior

It doesn't

### How to Reproduce?

open [github](https://github.com/keycloak/keycloak-k8s-resources)

### Anything else?

Just an automation issue I think

**Comment by vmuzikar** [comment]
Hello, if this is still valid, could you please open an issue in the [main Keycloak repository](https://github.com/keycloak/keycloak)? This repository is not monitored or used for tracking issues.

Thank you.
