### ISSUE TITLE
Feature request: Update the readme to explain what this repository aims to achieve

### ISSUE THREAD

**Issue by a-nldisr** [keycloak/keycloak-k8s-resources#16]
### Description

**Feature request**
Currently, the README.md is an empty page, in short, describe what this repository is about and what problems it is created to fix. 

**Background**
I was looking if Keycloak has CRDs to automatically create application tokens in kubernetes secrets, had to go through code to see if this repository matches that solution

**What will it fix**
- Wrong expectations
- Clear introduction and scope of the repository

**Comment by tadavid-cae** [comment]
PLEASE GIVE SOME HINTS OR EXAMPLES AT LEAST 🥲🥲🥲🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼

**Comment by vmuzikar** [comment]
Hello, if this is still valid, could you please open an issue in the [main Keycloak repository](https://github.com/keycloak/keycloak)? This repository is not monitored or used for tracking issues.

Thank you.
