### ISSUE TITLE
Missing openshift.yml for 23.0.0 and later

### ISSUE THREAD

**Issue by oyviaase** [keycloak/keycloak-k8s-resources#17]
### Describe the bug

I'm unable to upgrade my `openshift.yml` based operator to 23.0.0

### Version

22.0.5

### Expected behavior

Be able to download the new `openshift.yml` from the repo

### Actual behavior

I can't download it because it doesn't exists

### How to Reproduce?

Run the following command
```
wget https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/23.0.1/kubernetes/openshift.yml
```
And see that it gets a 404 error message

### Anything else?

I have tried to look in the changelog for any documentation on wheather or not it har been deprecated or not

**Comment by vmuzikar** [comment]
The `openshift.yml` file was not necessary as it didn't have any meaningful differences from `kubernetes.yml`, hence it was removed.
