### ISSUE TITLE
Install without OLM

### ISSUE THREAD

**Issue by patsys** [keycloak/keycloak-k8s-resources#20]
### Description

I have not found any offical Install methode without OLM.

I'm working with Flux for Infrastructure and Argocd for other Applications. For me the best case is a officel helm chart.

The minimal I need a Stable  branch I can use in flux with a semantic version without breaking changes. And a Readme do tell this.

Best Reguard
Patsys

### Motivation

Make Keyloak Operator as standard not only use OLM

### Details

* Officel Helmchart
*  Readme

**Comment by vmuzikar** [comment]
Please see https://www.keycloak.org/operator/installation#_installing_by_using_kubectl_without_operator_lifecycle_manager
