### ISSUE TITLE
Removing  tags and docker-images

### ISSUE THREAD

**Issue by propyless** [keycloak/keycloak-k8s-resources#21]
### Describe the bug

I deployed the version 24.0.0 version of the keycloak-operator the same day that it was released following the guide from https://www.keycloak.org/operator/installation (not using OLM). Today, when firing up the minikube cluster, I noticed that the keycloak operator was not starting up and getting Image pullback. So I saw in Quay, and the github repository that the 24.0.0 release has been removed and purged.

This was quite confusing to me especially as there are release notes https://www.keycloak.org/docs/24.0.0/release_notes/ for this 24.0.0 release.

If its a patch, perhaps a new release with 24.0.0-1, Or in this repository reference images to the major.minor tag?

### Version

24.0.0

### Expected behavior

Any old images/releases should not be deleted.

### Actual behavior

Image is removed and no longer pullable

### How to Reproduce?

Can't reproduce it now since you've dont keep the branches and just have "releases"

**Comment by propyless** [comment]
Nevermind, I read the release notes for 24.0.1, I guess this was the best choice considering.

**Comment by propyless** [comment]
but on the other hand.. https://www.keycloak.org/docs/24.0.1/release_notes/
It says to update the migration model to 24.0.0 from 999, but is this for the OLM database?

Looking at the postgresql database for KC I see this..

```
keycloak=# SELECT * from migration_model;
  id   | version | update_time 
-------+---------+-------------
 ldhhe | 24.0.0  |  1709621127
```

Im pretty sure I installed it quite early, same day as the release. 

Looking at the CRD metadata which i installed same day, and the c
```
Creation Timestamp:  2024-03-04T12:14:00Z                                                
CreationTimestamp:      Mon, 04 Mar 2024 13:14:09 +0100                                                                                                                               │                                                                                          
```

**Comment by vmuzikar** [comment]
Hello, if this is still valid, could you please open an issue in the [main Keycloak repository](https://github.com/keycloak/keycloak)? This repository is not monitored or used for tracking issues.

Thank you.
