### ISSUE TITLE
Trivy RBAC report [severity HIGH]

### ISSUE THREAD

**Issue by cp319391** [keycloak/keycloak-k8s-resources#23]
### Describe the bug

keycloak version: 24.0.2
We did a Trivy scan on our cluster. 
It reported HIGH vulnerability fixes for below roles.

- keycloak-operator-role 

![image](https://github.com/keycloak/keycloak-k8s-resources/assets/67651406/4e2d6cfe-f265-4a41-9ac8-bc146e59afb1)

in the keycloak-operator-role `network` resource described as below 
![image](https://github.com/keycloak/keycloak-k8s-resources/assets/67651406/b1b8e5e9-9e0c-4db6-b2e3-7c25700fb729)

the networking resource like ingresses are only allowed `get`, `list` and `watch` 

Questions: 
1. As we can also see networking resources in the `keycloakcontroller-cluster-role`, are the networking resource like `ingresses` at all need for both the role `keycloakcontroller-cluster-role`  and `keycloak-operator-role` ? 

2. If yes, can we limit the verbs to `get`, `list` and `watch` ? What could be the possible impact of it or is it doable without breaking the service ? Can it be corrected or changed in the future releases. 

### Version

24.0.2

**Comment by vmuzikar** [comment]
Hello, if this is still valid, could you please open an issue in the [main Keycloak repository](https://github.com/keycloak/keycloak)? This repository is not monitored or used for tracking issues.

Please see also [instructions on how to properly report a security vulnerability](https://www.keycloak.org/security.html).

Thank you.
