### ISSUE TITLE
Add sidecar to Keycloack deployment

### ISSUE THREAD

**Issue by yeplaa** [keycloak/keycloak-k8s-resources#24]
### Description

I would like to add a container sidecar to Keycloack deployment. Is it possible to create this sidecar with  the Keycloak CR?

**Comment by vmuzikar** [comment]
Hello, if this is still valid, could you please open an issue in the [main Keycloak repository](https://github.com/keycloak/keycloak)? This repository is not monitored or used for tracking issues.

Thank you.
