### ISSUE TITLE
Provide namespace-only configuration

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak-k8s-resources#6]
### Description

The previous operator provided YAML files, which could be referenced directly via Kustomize, that installed the operator in the provided namespace.

This repository again provides such YAML files, but installs the operator cluster wide. Which requires `ClusterRoles` and impacts the full cluster.

I think it would be helpful to have the old behavior again (one namespace only), as this also seems to be default for the OLM based installation of the operator.

### Motivation

Especially in a multi-user environment, it might be beneficial to have multiple versions of the operator confined to different namespaces.

**Comment by vmuzikar** [comment]
Hello, if this is still valid, could you please open an issue in the [main Keycloak repository](https://github.com/keycloak/keycloak)? This repository is not monitored or used for tracking issues.

Thank you.
