### ISSUE TITLE
Don't use version in pod selector

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak-k8s-resources#7]
### Describe the bug

The deployment uses the version of keycloak in the pod selector. However, this prevents an upgrade of the operator, as the pod selector is immutable:

```
The Deployment "keycloak-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"keycloak-operator", "app.kubernetes.io/version":"18.0.1"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

### Version

18.0.0

### Expected behavior

It should be possible to upgrade the operator using standard Kubernetes tools (`kubectl apply`).

### Actual behavior

The operator is not upgradable.

### How to Reproduce?

* Install operator 18.0.0
* Try to upgrade by applying the new (18.0.1) version

**Comment by rustygreen** [comment]
Same issue. I'm currently on version 20.0.3 and can't upgrade to 21.0.0 due to this issue.

**Comment by Robbilie** [comment]
this is super annoying, @vmuzikar this makes using it with flux/gitops "impossible", could that be stripped out?

**Comment by atrifyllis** [comment]
Is there  a workaround for this issue? How do people upgrade operator at the moment?

**Comment by tsndqst** [comment]
It looks like the version label selector was removed in [24.0.1](https://github.com/keycloak/keycloak-k8s-resources/compare/23.0.7...24.0.1#diff-2f5a8bca5ffd3b1ea4a87cfc724f55b7242a219e85ffce79a9d39d7219ae628cL191).

There might be a better way to upgrade but I just deleted the keycloak deployment before applying 24.0.2.

**Comment by vmuzikar** [comment]
Resolving since this was fixed with 24.
